name: test project
on: push
jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - name: get code
         uses: actions/checkout@v4
       - name: setup nodejs
         uses: actions/setup-node@v3 
         with: 
           node-version: 18
       - name: install nodejs
         run: npm ci  
       - name: npm test
         run: npm test       

