name: first workflow
on: workflow_dispatch
jobs:
   first-job: 
      runs-on: ubuntu-latest
      steps:
         - name: print greeting
           run: echo "Helloworld"
         - name: print goodby
           run: echo "done"  